app:
  path: /Users/liangyongrui/IdeaProjects/easy-nas-server

adminConfigPath: ${app.path}/easy-nas/admin-config.yml

defaultFileSavePaths:
  master: ${app.path}/easy-nas/easy-nas-data/file/
  backup: null
defaultGeneralInformationPath:
  master: ${app.path}/easy-nas/easy-nas-data/general-information/
  backup: null
