server:
  port: 8888

ftp:
  port: 2222

adminConfigPath: ${user.home}/.easy-nas/admin-config.yml

defaultFileSavePaths:
  master: ${user.home}/.easy-nas/easy-nas-data/file/
  backup: null
defaultGeneralInformationPath:
  master: ${user.home}/.easy-nas/easy-nas-data/general-information/
  backup: null
